# Generated by Django 4.2.28 on 2026-02-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_mode_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
